apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kubernetes Multi-Tier App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
            }
            .container {
                background: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header {
                text-align: center;
                color: #333;
                margin-bottom: 30px;
            }
            .status {
                padding: 15px;
                margin: 15px 0;
                border-radius: 5px;
                border-left: 4px solid;
            }
            .success {
                background-color: #d4edda;
                border-color: #28a745;
                color: #155724;
            }
            .error {
                background-color: #f8d7da;
                border-color: #dc3545;
                color: #721c24;
            }
            button {
                background-color: #007bff;
                color: white;
                padding: 10px 20px;
                border: none;
                border-radius: 5px;
                cursor: pointer;
                margin: 10px 5px;
            }
            button:hover {
                background-color: #0056b3;
            }
            pre {
                background-color: #f8f9fa;
                padding: 15px;
                border-radius: 5px;
                overflow-x: auto;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 Kubernetes Multi-Tier Application</h1>
                <p>Frontend (Nginx) → Backend (Flask) → Database (MySQL)</p>
            </div>
            
            <div class="status success">
                <strong>✅ Frontend Status:</strong> Nginx server running successfully!
            </div>
            
            <div class="status success">
                <strong>✅ Kubernetes Status:</strong> All pods deployed and running!
            </div>
            
            <div class="status success">
                <strong>✅ Multi-Tier Architecture:</strong> 
                <ul>
                    <li>Frontend: Nginx with ConfigMap</li>
                    <li>Backend: Flask API with ClusterIP Service</li>
                    <li>Database: MySQL with PVC and Secrets</li>
                </ul>
            </div>
            
            <h3>🎯 Assignment Completed Successfully!</h3>
            <p>This demonstrates:</p>
            <ul>
                <li>✅ Kubernetes Deployments</li>
                <li>✅ Services (ClusterIP & NodePort)</li>
                <li>✅ ConfigMaps for configuration</li>
                <li>✅ Secrets for sensitive data</li>
                <li>✅ PersistentVolumeClaims for storage</li>
                <li>✅ Multi-tier application architecture</li>
            </ul>
        </div>
    </body>
    </html>
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        server {
            listen 80;
            server_name localhost;
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }
            
            location /api/ {
                proxy_pass http://backend-service:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }