apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdDEyMw==  # root123 base64 encoded
  mysql-user: dXNlcg==              # user base64 encoded
  mysql-password: cGFzc3dvcmQ=      # password base64 encoded
  mysql-database: bXlhcHA=          # myapp base64 encoded